# Site settings
title: DemonHuner的技术博客
description: '记录在工作学习中的笔记，专注于分享移动开发领域高质量文章，努力做一个徘徊于牛A和牛C之间的人'
url: 'https://github.com/zhangyinglong/DemonHunter'

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

blog_button:
    title: 博客
    description: 访问博客

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
# comment:
#     disqus: zhangyinglong
#     duoshuo: zhangyinglong

# Social
social:
    # weibo: zhangyinglong
    github: zhangyinglong
    # twitter: zhangyinglong
    mail: zyl04401@gmail.com

theme: jekyll-theme-cayman

# Google Analytics
# ga:
#     id: UA-xxxx-x
#     host: xxxx.com